# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=120)),
                ('s_address', models.CharField(max_length=120)),
                ('b_address', models.CharField(max_length=120)),
                ('s_type', models.CharField(max_length=120)),
                ('p_type', models.CharField(max_length=120)),
                ('card_name', models.CharField(max_length=120)),
                ('card_num', models.CharField(max_length=16)),
                ('card_exp_month', models.CharField(max_length=2)),
                ('card_exp_year', models.CharField(max_length=2)),
            ],
        ),
    ]
