# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='b_address',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='card_exp_month',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='card_exp_year',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='card_num',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='p_type',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='r_name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='s_address',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='s_type',
        ),
    ]
