# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170424_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='b_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='summary',
            name='card_exp_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='summary',
            name='card_exp_year',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='summary',
            name='card_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='summary',
            name='card_num',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='summary',
            name='p_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='summary',
            name='r_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='summary',
            name='s_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='summary',
            name='s_type',
            field=models.CharField(default='', max_length=120),
        ),
    ]
